name: R Data Analysis and Commit

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'  # Runs at the start of every 2nd hour

permissions:
  contents: write

jobs:
  analysis_and_commit:
    runs-on: ubuntu-22.04
    env:
      TZ: "Africa/Nairobi"  # Setting time zone for the job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install system dependencies for tidyverse
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev libicu-dev libblas-dev liblapack-dev zlib1g-dev libudunits2-dev libgdal-dev libgeos-dev libproj-dev

    - name: Set up Pandoc
      uses: r-lib/actions/setup-pandoc@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.0.4'  # Replace this with your desired R version

    - name: Install R packages
      env:
        GITHUB_PAT: ${{secrets.GH_PAT }}
      run: |
        Rscript -e "install.packages(c('ggplot2','dplyr', 'data.table', 'remotes', 'rmarkdown'), repos = 'http://cran.rstudio.com')"
        Rscript -e "remotes::install_github('dickoa/rhdx', upgrade = 'never' )"

    - name: Run R script
      run: Rscript R/run_data_set.R

    - name: Commit files
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config pull.rebase false
          git pull origin main
          date=$(date +'%Y-%m-%d')
          git add .
          git commit -m "automatic updates $date" || echo "Nothing to update"

    - name: Push updated data
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GH_PAT}}
          branch: main




